
services:
  # Use the production definition but add local-only settings
  trading_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app # Mount app code for hot-reloading
    ports:
      - "8001:8000" # Expose to host for direct API testing
    env_file:
      - .env.local
    depends_on:
      - postgres
      - pgbouncer
      - librarian-mock

  postgres:
    image: postgres:17
    container_name: local_postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    networks:
      - central-data-platform
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: pgbouncer/pgbouncer
    container_name: local_pgbouncer
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/app_db
      - PG_USER=user
    ports:
      - "6432:6432"
    networks:
      - central-data-platform
    depends_on:
      postgres:
        condition: service_healthy

  # Mock Librarian Service using Nginx to serve a static JSON response
  librarian-mock:
    image: nginx:alpine
    container_name: local_librarian_mock
    volumes:
      - ./tests/mocks/librarian:/usr/share/nginx/html:ro
    networks:
      - central-data-platform

  nginx:
    image: nginx:latest
    container_name: local_nginx
    ports:
      - "8080:80" # We'll access the app via http://localhost:8080
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./trading-app-frontend/dist:/var/www/static:ro
    networks:
      - central-data-platform
    depends_on:
      - trading_app

networks:
  central-data-platform:
    name: central-data-platform